services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
      - CLI_ARGS= #optional
    volumes:
      - config:/config
      - backups:/backups
      - ../:/HOST_REPO
      - /var/lib/docker/:/HOST_DOCKER
#    ports:
#      - 8200:8200
    restart: unless-stopped
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SUB_DOMAIN}.entrypoints=http"
      - "traefik.http.routers.${SUB_DOMAIN}.rule=Host(`${SUB_DOMAIN}.${DOMAIN}`)"
      - "traefik.http.middlewares.${SUB_DOMAIN}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${SUB_DOMAIN}.middlewares=${SUB_DOMAIN}-https-redirect"
      - "traefik.http.routers.${SUB_DOMAIN}-secure.entrypoints=https"
      - "traefik.http.routers.${SUB_DOMAIN}-secure.rule=Host(`${SUB_DOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.${SUB_DOMAIN}-secure.tls=true"
      - "traefik.http.routers.${SUB_DOMAIN}-secure.service=${SUB_DOMAIN}"
      - "traefik.http.services.${SUB_DOMAIN}.loadbalancer.server.port=8200"
      - "traefik.docker.network=proxy"
#      - "traefik.http.routers.${SUB_DOMAIN}-secure.middlewares=authentik@file"       # Authentik Proxy

volumes:
  config:
  backups:

networks:
  proxy:
    external: true