services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Berlin
      - CLI_ARGS= #optional
    volumes:
      - config:/config
      - backups:/backups
      - ../:/source/compose
      - /var/lib/docker/:/source/docker
    ports:
      - 8200:8200
    restart: unless-stopped

volumes:
  config:
  backups:
