---

services:
  portainer:
    image: portainer/portainer-${VARIANTE}:latest # change -ee to -ce for community edition
    container_name: portainer
#    ports:
#      - ${AGENT_PORT}:8000
#      - 9443:9443
#      - 9000:9000 # for http
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      proxy:
      agent_network:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SUB_DOMAIN}.entrypoints=http"
      - "traefik.http.routers.${SUB_DOMAIN}.rule=Host(`${SUB_DOMAIN}.${DOMAIN}`)"
      - "traefik.http.middlewares.${SUB_DOMAIN}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${SUB_DOMAIN}.middlewares=${SUB_DOMAIN}-https-redirect"
      - "traefik.http.routers.${SUB_DOMAIN}-secure.entrypoints=https"
      - "traefik.http.routers.${SUB_DOMAIN}-secure.rule=Host(`${SUB_DOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.${SUB_DOMAIN}-secure.tls=true"
      - "traefik.http.routers.${SUB_DOMAIN}-secure.service=${SUB_DOMAIN}"
      - "traefik.http.services.${SUB_DOMAIN}.loadbalancer.server.port=9000"
      - "traefik.docker.network=proxy"

  agent:
    image: portainer/agent:latest
    container_name: portainer-agent
    restart: unless-stopped
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_PORT: 9001
      # LOG_LEVEL: debug
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
    networks:
      agent_network:

volumes:
  data:

networks:
  agent_network:
  proxy:
    external: true
